FROM python:3.9
#SINTALL SSH CLIENT
RUN apt-get update && apt-get install -y openssh-client

#SET ENVIRONMENT VARIABLES
ENV PYTHONUNBUFFERED 1

#SET WORKDIR DIRECTORY
WORKDIR /app

#COPY REQUIREMENTS FILE
COPY requirements.txt /app/requirements.txt
#INSTALL REQUIREMENTS
RUN pip install -r requirements.txt

#COPY PROJECT FILES
COPY . /app

#start the ssh tunnel
CMD python manage.py runserver 0.0.0.0:8000